// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Agencia
{
    public string Codagencia { get; set; }

    public string Nombre { get; set; }

    public string Descripcion { get; set; }

    public string Observacion { get; set; }

    public string Longitud { get; set; }

    public string Latitud { get; set; }

    public string Tipo { get; set; }

    public int? CampoA { get; set; }

    public string CampoB { get; set; }

    public string Codcliente { get; set; }

    public string Horarioatenciond { get; set; }

    public string Codfrecuencia { get; set; }

    public string Codcia { get; set; }

    public int? Estado { get; set; }

    public string CodProv { get; set; }

    public string CodCanton { get; set; }

    public string Horarioatencionh { get; set; }

    public string Horarioatenciondm { get; set; }

    public string Horarioatencionhm { get; set; }

    public int? Centrocostos { get; set; }

    public DateTime? Fecrea { get; set; }
}