// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Cliente
{
    public string Codcliente { get; set; }

    public string Ruc { get; set; }

    public string Replegal { get; set; }

    public DateTime? Fechacontinicio { get; set; }

    public DateTime? Fechacontfinal { get; set; }

    public string Descripcion { get; set; }

    public string Observacion { get; set; }

    public string Telfclimanteni { get; set; }

    public string Correomantenimiento { get; set; }

    public string Telfpago { get; set; }

    public string Correopago { get; set; }

    public string Coduser { get; set; }

    public string Codcia { get; set; }

    public string Nombre { get; set; }

    public string Tipo { get; set; }

    public string NombreMantenimiento { get; set; }

    public string NombrePago { get; set; }

    public string Extension1 { get; set; }

    public string Extension2 { get; set; }
}