// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Ticketresolucion
{
    public int IdRequerimiento { get; set; }

    public int? Idcliente { get; set; }

    public string UrlA { get; set; }

    public string UrlB { get; set; }

    public int? Estado { get; set; }

    public string MensajeDelProblema { get; set; }

    public string MensajeResolucion { get; set; }

    public string Obervacion { get; set; }

    public int? Iduser { get; set; }

    public DateTime? Fechacrea { get; set; }
}