// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class UsuarioPortalTicket
{
    public int Id { get; set; }

    public string Usuario { get; set; }

    public string Password { get; set; }

    public string Correo { get; set; }

    public string IdCliente { get; set; }

    public string Rol { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string CodUser { get; set; }

    public string Active { get; set; }
}