// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ticketsRequerimientosBackend.Models;

public partial class Usuario
{
    public string Coduser { get; set; }

    public string Email { get; set; }

    public string Nombre { get; set; }

    public string Apellido { get; set; }

    public string Cedula { get; set; }

    public string Cargo { get; set; }

    public string Contrasenia { get; set; }

    public string Estado { get; set; }

    public int? Edad { get; set; }

    public string Tipo { get; set; }

    public string Movilidad { get; set; }

    public string Codcaracteristicas { get; set; }

    public int? Valoracion { get; set; }

    public string CodProvincia { get; set; }

    public string CodCanton { get; set; }

    public string CodSexo { get; set; }

    public string CodEstadoCivil { get; set; }

    public string CodDepartamento { get; set; }

    public string CodLicencia { get; set; }

    public string Telf { get; set; }

    public string Direccion { get; set; }

    public string CodCia { get; set; }

    public DateTime? Fecingreso { get; set; }

    public DateTime? Fecsalida { get; set; }
}